#PBS -N tdp5-hk
# temps en heure:minutes:secondes
#PBS -l walltime=00:03:00
# nombre de noeuds et de coeurs
#PBS -l nodes=1:ppn=8
#PBS -l naccesspolicy=singlejob
module load compiler/intel mpi/openmpi/current
# répertoire de travail dans lequel on soumet le batch
cd 5tdp-hk/bin
export MKL_NUM_THREADS=4
export MYLIB_NUM_THREADS=4
###./test-myblas
###./test-mylapack
### ./benchmark
### mpiexec -np 2 ./benchmark
### mpiexec -np 4 ./benchmark
mpiexec -np 8 ./benchmark